config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'posts#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  resources :users
  resources :posts, only: [:new, :index, :show, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true, length: {minimum: 3, maximum: 35}
	validates :body,  presence: true, length: {minimum: 3, maximum: 500}
	validates :user_id, presence: true

	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	before_save :downcase_email
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  has_many :posts

  def User.digest(string)
	  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
	                                                BCrypt::Engine.cost
	  BCrypt::Password.create(string, cost: cost)
  end

  #generate a new random token
  def User.new_token
  	SecureRandom.urlsafe_base64
  end

  #remembers a user in the database for persistent login
  def remember
  	self.remember_token = User.new_token
  	update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  private
  	def downcase_email
  		self.email.downcase!
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def logged_in_user
  	unless logged_in?
  		flash[:danger] = "Please log in before creating a post."
  		redirect_to login_url
  	end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :logged_in_user, only: [:new, :create]

	def new
		@post=Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user_id=current_user.id
		if @post.save
			flash[:info] = "You have successfully created a new post."
			redirect_to root_url
		else
			render 'new'
		end
	end

	def index
		@posts = Post.all
	end

	private

		def post_params
			params.require(:post).permit(:title, :body)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by(email: params[:session][:email].downcase)
  	if @user && @user.authenticate(params[:session][:password])
  		log_in @user
  		params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
  		flash[:notice] = "You have successfully logged in."
  		redirect_to root_url
  	else
  		flash.now[:danger] = 'Invalid email/password combination'
  		render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def log_in(user)
		session[:user_id] = user.id
	end

	# Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
  	forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Coded by <a href="https://github.com/MarshallM1">B.Morris</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Members Only", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "New Post", new_post_path%>
          <li><%= link_to "Log out", logout_path, method: :delete %>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<a href="#" class="list-group-item">
	<h4 class="list-group-item-heading"> <%= post.title %></h4>
	<p class="list-group-item-text"><%= post.body %></p>
	<div class="posted-by">
		<p class="list-group-item-text">
			Posted By
			<% if logged_in? %>
				<%= User.find_by(id: post.user_id).name %>
			<% else %>
				Anon
			<% end %>
		</p>
	</div>
</a>

app/views/posts/index.html.erb
<% provide(:title, "Home | Members Only") %>

<h1>All posts</h1>

<div class="container">
  <div class="list-group">
		<div class="posts">
  		<%= render @posts %>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<% provide(:title, "Create a Post | Members Only") %>

<h1>Create a Post</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          The form contains <%= pluralize(@post.errors.count, "error") %>.
        </div>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      </div>
    <% end %>
    <%= form_for(:post, url: posts_path) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>